# Generated by Django 3.2 on 2021-07-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('RegistrationNo', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
