# Generated by Django 3.2 on 2021-07-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_users_registrationno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
