# Generated by Django 3.2 on 2021-07-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegister',
        ),
    ]
